# -*- coding: utf-8 -*-
"""Untitled55.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GsSNtxcgN2WIez662FFivoOqZ3KTZm5o
"""

import matplotlib.pyplot as plt
import pandas as pd

def plot_bubble_interactive(merged, bubble_type, company='All companies'):
    assert isinstance(merged, pd.DataFrame), "merged must be a pandas DataFrame"
    assert not merged.empty, "merged DataFrame cannot be empty"
    assert 'bubble_type' in merged.columns, "merged must contain 'bubble_type' column"
    assert 'date' in merged.columns, "merged must contain 'date' column"
    assert isinstance(bubble_type, str), "bubble_type must be a string"
    assert isinstance(company, str), "company must be a string"
    
    # Filter by bubble
    df = merged[merged['bubble_type'] == bubble_type].copy()

    if df.empty:
        print(f"No data for bubble {bubble_type}")
        return

    # ------------------------------
    # Plot cumulative bubble index for all companies
    # ------------------------------
    if company == 'All companies':
        ts = df.groupby('date')['bubble_index'].mean()
        plt.figure(figsize=(12,5))
        plt.plot(ts, label=f"{bubble_type.upper()} Bubble Index", color='blue')
        plt.axhline(0, linestyle='--')
        plt.axhline(2, color='red', linestyle='--', label='Bubble Threshold')
        plt.title(f"Cumulative Bubble Index: {bubble_type.upper()}")
        plt.xlabel("Date")
        plt.ylabel("Bubble Index (Z-score)")
        plt.legend()
        plt.grid(True)
        plt.show()
        return

    # ------------------------------
    # Plot for specific company
    # ------------------------------
    assert 'tic' in merged.columns, "merged must contain 'tic' column"
    assert 'conm' in merged.columns, "merged must contain 'conm' column"
    assert 'prc' in merged.columns, "merged must contain 'prc' column"
    assert 'saleq' in merged.columns, "merged must contain 'saleq' column"
    assert 'mktcap' in merged.columns, "merged must contain 'mktcap' column"
    
    comp_df = df[df['tic'] == company].sort_values('date')
    if comp_df.empty:
        print(f"No data for company {company} in bubble {bubble_type}")
        return

    company_name = comp_df['conm'].iloc[0]

    # 1) Price and sales
    plt.figure(figsize=(12,5))
    plt.plot(comp_df['date'], comp_df['prc'], label='Price', linewidth=2)
    plt.plot(comp_df['date'], comp_df['saleq'], label='Sales (quarterly)', linewidth=2)
    plt.title(f"{company_name}: Price vs Sales")
    plt.xlabel("Date")
    plt.ylabel("Price / Sales")
    plt.legend()
    plt.grid(True)
    plt.show()

    # 2) P/S ratio with threshold
    comp_df['ps_ratio'] = comp_df['mktcap'] / comp_df['saleq']
    comp_df['ps_z'] = (comp_df['ps_ratio'] - comp_df['ps_ratio'].mean()) / comp_df['ps_ratio'].std()

    plt.figure(figsize=(12,5))
    plt.plot(comp_df['date'], comp_df['ps_ratio'], label='P/S Ratio', color='blue', linewidth=2)
    plt.axhline(comp_df['ps_ratio'].mean() + 2*comp_df['ps_ratio'].std(), color='red', linestyle='--', label='Z=2 Threshold')
    plt.title(f"{company_name}: P/S Ratio with Bubble Threshold")
    plt.xlabel("Date")
    plt.ylabel("P/S Ratio")
    plt.legend()
    plt.grid(True)
    plt.show()

    # 3) Display company name
    print(f"Company: {company_name}")
import ipywidgets as widgets
from ipywidgets import interact

# Initialize bubble dropdown
initial_bubble = merged['bubble_type'].unique()[0]
bubble_dropdown = widgets.Dropdown(
    options=merged['bubble_type'].unique(),
    description='Bubble:',
    value=initial_bubble
)

# Company dropdown
def get_companies_for_bubble(df, bubble):
    assert isinstance(df, pd.DataFrame), "df must be a pandas DataFrame"
    assert 'bubble_type' in df.columns, "df must contain 'bubble_type' column"
    assert 'tic' in df.columns, "df must contain 'tic' column"
    assert isinstance(bubble, str), "bubble must be a string"
    
    df_b = df[df['bubble_type'] == bubble]
    companies = ['All companies'] + sorted(df_b['tic'].dropna().unique().tolist())
    return companies

company_dropdown = widgets.Dropdown(
    options=get_companies_for_bubble(merged, initial_bubble),
    description='Company:',
    value='All companies'
)

# Update company dropdown when bubble changes
def update_company_options(change):
    new_bubble = change['new']
    company_dropdown.options = get_companies_for_bubble(merged, new_bubble)
    company_dropdown.value = 'All companies'

bubble_dropdown.observe(update_company_options, names='value')

# Interactive plot
interact(plot_bubble_interactive,
         merged=widgets.fixed(merged),
         bubble_type=bubble_dropdown,
         company=company_dropdown)